# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41103472bea031de4f568d98ab0abeb69811e3995c1a5d40b3632281466da3f41279d241c3d94b12c1d27fb72326634985bdf3b540834172403b7cbc246d07e1

test:
  secret_key_base: 24f3f4d790c5b70e1694c8b9b7a1a5a7483c51e035f1af2f195e1c66a1b7a829005e2e3eaeea17cdf20ac9c039ef9f22c9aade5177b5547991d29489e6c2999f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
